# Generated by Django 5.0.4 on 2024-05-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBR', 'GBR'), ('JOD', 'JOD'), ('JPY', 'JPY')], default='USD', max_length=3)),
                ('total', models.PositiveIntegerField(default=0)),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket', to='products.frame')),
                ('lens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket', to='products.lens')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBR', 'GBR'), ('JOD', 'JOD'), ('JPY', 'JPY')], default='USD', max_length=3)),
                ('total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.JSONField(default=dict, verbose_name='frame')),
                ('lens', models.JSONField(default=dict, verbose_name='lens')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', related_query_name='purchase', to='orders.order')),
            ],
        ),
    ]
