# Generated by Django 5.0.4 on 2024-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBR', 'GBR'), ('JOD', 'JOD'), ('JPY', 'JPY')], default='USD', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'abstract': False,
                'unique_together': {('price', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBR', 'GBR'), ('JOD', 'JOD'), ('JPY', 'JPY')], default='USD', max_length=3)),
                ('colour', models.CharField(max_length=32)),
                ('prescription_type', models.CharField(choices=[('fashion', 'Fashion'), ('single_vision', 'Single Vision'), ('varifocal', 'Varifocal')], max_length=13)),
                ('lens_type', models.CharField(choices=[('classic', 'Classic'), ('blue_light', 'Blue Light'), ('transition', 'Transition')], max_length=10)),
            ],
            options={
                'abstract': False,
                'unique_together': {('price', 'currency')},
            },
        ),
    ]
